---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: fedora:35
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
